### ISSUE TITLE
Get Heading / Direction

### ISSUE THREAD

**Issue by yeldarby** [JuanIrache/DJI_SRT_Parser#78]
Hi, is it possible to get the compass heading at a given timestamp from the SRT files? And if not, maybe compute it from the direction of travel?

Also any possibility of getting the gimbal inclination?

**Comment by JuanIrache** [comment]
Generally, the subtitle logs don't include orientation. I think on some
models they do, and they are labelled as F.PRY and G.PRY (PRY is pith,
roll, yaw, and I suppose G stanfs for gimbal).

This library just extracts the data, but you could compute direction of
travel in your own code by comparing consecutive coordinates.

Juan Irache
Independent Software Developer
https://goprotelemetryextractor.com/ <https://prototyping.barcelona/>

**Comment by yeldarby** [comment]
Thanks! I ended up pulling the full flight logs via Airdata which had the full telemetry that [let me match up my video with a map](https://github.com/roboflow-ai/dji-aerial-georeferencing).

https://user-images.githubusercontent.com/870796/189566872-7fd4bf61-cbe2-417d-80f3-51083a05e3a7.mp4

**Comment by JuanIrache** [comment]
Really nice result!
